### ISSUE TITLE
Not working with latest client docker image

### ISSUE THREAD

**Issue by ratosh** [aiarena/local-play-bootstrap#4]
Getting this error when trying to start with latest docker image but it works with version 1.0.12:
```
λ docker-compose up                                                                                                       
Pulling arena-client (aiarena/arenaclient:)...                                                                            
latest: Pulling from aiarena/arenaclient                                                                                  
42c077c10790: Pull complete                                                                                               
f63e77b7563a: Pull complete                                                                                               
bd5fdadae976: Pull complete                                                                                               
205491f53016: Pull complete                                                                                               
df18705c85c3: Pull complete                                                                                               
e3c13ce9ffc6: Pull complete                                                                                               
f0abbb2e2bb0: Pull complete                                                                                               
Digest: sha256:679e3a884d45b60395d0ac5432f206f2728ce850c4a09a4e0ea9f1d96b377b2a                                           
Status: Downloaded newer image for aiarena/arenaclient:latest                                                             
Recreating local-aiarena_arena-client_2 ... done                                                                          
Attaching to local-aiarena_arena-client_2                                                                                 
arena-client_2  | Traceback (most recent call last):                                                                      
arena-client_2  |   File "/root/aiarena-client/arenaclient/configs/default_config.py", line 88, in <module>               
arena-client_2  |     from_model_import_star(module_to_import)                                                            
arena-client_2  |   File "/root/aiarena-client/arenaclient/configs/default_config.py", line 71, in from_model_import_star 
arena-client_2  |     mdl = importlib.import_module(module)                                                               
arena-client_2  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module                     
arena-client_2  |     return _bootstrap._gcd_import(name[level:], package, level)                                         
arena-client_2  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                                       
arena-client_2  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                                    
arena-client_2  |   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked                            
arena-client_2  | ModuleNotFoundError: No module named 'arenaclient.configs.REMOTE_config_template'                       
arena-client_2  |                                                                                                         
arena-client_2  | During handling of the above exception, another exception occurred:                                     
arena-client_2  |                                                                                                         
arena-client_2  | Traceback (most recent call last):                                                                      
arena-client_2  |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main                            
arena-client_2  |     return _run_code(code, main_globals, None,                                                          
arena-client_2  |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code                                       
arena-client_2  |     exec(code, run_globals)                                                                             
arena-client_2  |   File "/root/aiarena-client/arenaclient/__main__.py", line 7, in <module>                              
arena-client_2  |     from .configs import default_config as cfg                                                          
arena-client_2  |   File "/root/aiarena-client/arenaclient/configs/default_config.py", line 91, in <module>               
arena-client_2  |     raise f"Could not locate a config template called {module_to_import}!"                              
arena-client_2  | TypeError: exceptions must derive from BaseException                                                    
local-aiarena_arena-client_2 exited with code 1                                                                           
```

**Comment by ratosh** [comment]
Issue was related to some other config changes I made.
